title:              Yaroslav Nasonov
email:              yaroslav.nasonov@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Yaroslav Nasonov
baseurl:            "/"
url:                "https://yarikinez.github.io"

# Social Profiles
twitter_username:   
github_username:    yarikinez
facebook_username:  yaroslav_nasonov
instagram_username: yarikinez
linkedin_username:  yarikinez


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
